### ISSUE TITLE
Fix custom CSS 

### ISSUE THREAD

**Issue by Owen000** [GooseMod/Modules#10]
Fix custom css staying and not just having the module loading bar permanently stuck at the bottom and the custom css not loading.

**Comment by CanadaHonk** [comment]
Seems like GooseMod is trying to call a loading finished event handler even though it doesn't have one - investigating.

**Comment by CanadaHonk** [comment]
Nope, that is seemingly a separate issue.

**Comment by CanadaHonk** [comment]
Found the issue - using the wrong variable name when loading settings in the event handler. Releasing update with a fix.

**Comment by CanadaHonk** [comment]
Update released.
