### ISSUE TITLE
Bug: Custom css don't work correctly on start.

### ISSUE THREAD

**Issue by yShyboy** [GooseMod/Modules#12]
The things saved there don't work great at start, and stay that way until you do something in the custom css page.

Start:
![image](https://user-images.githubusercontent.com/64989316/100486564-29af5d00-30e3-11eb-8ff2-1d2b7e7f7c91.png)

After doing something in the window:
![image](https://user-images.githubusercontent.com/64989316/100486596-46e42b80-30e3-11eb-9327-93fb2c9a336b.png)

**Comment by CanadaHonk** [comment]
Should be solved in the latest Custom CSS updates.
