### ISSUE TITLE
Enhancement: Module store clear categories

### ISSUE THREAD

**Issue by hax4dazy** [GooseMod/Modules#62]
There's no easy way if you want to quickly disable your theme to clear the categories in the store, maybe there should be a button for that?

**Comment by CanadaHonk** [comment]
This should be in [the main Injector repo](https://github.com/GooseMod/Injector) as it relates to the Module Store UI?

**Comment by hax4dazy** [comment]
Whoops sorry lmao. Wasn't really sure where to put this

**Comment by CanadaHonk** [comment]
Fair enough lol, if you repost it there I'll close this.
