### ISSUE TITLE
Idea: No Notifs

### ISSUE THREAD

**Issue by kewdf** [GooseMod/Modules#72]
Ability to have invisible function similarly to Do Not Disturb, in which you won't receive notifications (or the sounds for them).

**Comment by CanadaHonk** [comment]
Hi, this repo is now beginning to be deprecated so please make an issue in [this repo for Module Store v2](https://github.com/GooseMod-Modules/Requests) instead. Thanks.

**Comment by kewdf** [comment]
Oh, didn't see it. Thank you.

**Comment by CanadaHonk** [comment]
No worries, thank you too.
