### ISSUE TITLE
Ideas: highlighted text actions

### ISSUE THREAD

**Issue by hax4dazy** [GooseMod/Modules#9]
You can highlight text and easily make it bold or put it in a spoiler tag

**Comment by hax4dazy** [comment]
![image](https://user-images.githubusercontent.com/16256978/98675819-0ce0fe80-235b-11eb-8587-b667355efddf.png)
Here's a quick mock up I made using inspect element

**Comment by adntaha** [comment]
You can do this with normal discord

**Comment by hax4dazy** [comment]
You mean manually add the elements to your text? I meant for this to be a shortcut

**Comment by DanielC7205** [comment]
> You mean manually add the elements to your text? I meant for this to be a shortcut

You can do Italics and Bold using Keyboard shortcuts, but yeah shortcuts wouldn't hurt.

**Comment by adntaha** [comment]
> > You mean manually add the elements to your text? I meant for this to be a shortcut
> 
> You can do Italics and Bold using Keyboard shortcuts, but yeah shortcuts wouldn't hurt.

Select text, and then double click it.

**Comment by valentinegb** [comment]
Oh uh, yeah @Oj18 or @hax4dazy, you should close this PR. The module you're describing is literally a feature in Discord already.
